services:
  - type: web
    name: pizza-delivery
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
